[2024-11-18T12:39:12.871+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T12:39:14.428+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_pipeline.transform_weather_data scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T12:39:14.820+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_pipeline.transform_weather_data scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T12:39:14.821+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-11-18T12:39:15.567+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): transform_weather_data> on 2024-11-17 00:00:00+00:00
[2024-11-18T12:39:16.144+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=381) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-18T12:39:16.226+0000] {standard_task_runner.py:72} INFO - Started process 390 to run task
[2024-11-18T12:39:16.071+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_pipeline', 'transform_weather_data', 'scheduled__2024-11-17T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl.py', '--cfg-path', '/tmp/tmpsklid95r']
[2024-11-18T12:39:16.237+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask transform_weather_data
[2024-11-18T12:39:17.671+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_pipeline.transform_weather_data scheduled__2024-11-17T00:00:00+00:00 [running]> on host a1d4e919f1b0
[2024-11-18T12:39:22.161+0000] {job.py:229} INFO - Heartbeat recovered after 12.48 seconds
[2024-11-18T12:39:23.786+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naphat' AIRFLOW_CTX_DAG_ID='weather_etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-17T00:00:00+00:00'
[2024-11-18T12:39:23.789+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T12:39:23.798+0000] {python.py:240} INFO - Done. Returned value was: {'Time of Record': '2024-11-18 12:31:57', 'Country': 'TH', 'City': 'Bangkok', 'Latitude': 13.75, 'Longitude': 100.5167, 'Current Weather': 'Clouds', 'Temperature (F)': 85.892, 'Feels Like (F)': 90.53600000000007, 'Minimun Temp (F)': 82.90400000000005, 'Maximum Temp (F)': 85.892, 'Pressure': 1010, 'Humidty': 59, 'Wind Speed': 1.78, 'Sunrise (Local Time)': '2024-11-17 23:19:15', 'Sunset (Local Time)': '2024-11-18 10:47:17'}
[2024-11-18T12:39:24.118+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T12:39:24.122+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_pipeline, task_id=transform_weather_data, run_id=scheduled__2024-11-17T00:00:00+00:00, execution_date=20241117T000000, start_date=20241118T123914, end_date=20241118T123924
[2024-11-18T12:39:24.733+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T12:39:26.065+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T12:39:26.171+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-18T12:39:26.237+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
