[2024-11-18T12:49:17.565+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T12:49:18.278+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_pipeline.load_weather_data manual__2024-11-18T12:48:06.879334+00:00 [queued]>
[2024-11-18T12:49:18.672+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_pipeline.load_weather_data manual__2024-11-18T12:48:06.879334+00:00 [queued]>
[2024-11-18T12:49:18.679+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-11-18T12:49:21.469+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_data> on 2024-11-18 12:48:06.879334+00:00
[2024-11-18T12:49:22.948+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_pipeline', 'load_weather_data', 'manual__2024-11-18T12:48:06.879334+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl.py', '--cfg-path', '/tmp/tmpcrkbyt8f']
[2024-11-18T12:49:23.111+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask load_weather_data
[2024-11-18T12:49:23.187+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=592) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-18T12:49:23.208+0000] {standard_task_runner.py:72} INFO - Started process 598 to run task
[2024-11-18T12:49:31.289+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_pipeline.load_weather_data manual__2024-11-18T12:48:06.879334+00:00 [running]> on host a1d4e919f1b0
[2024-11-18T12:49:31.409+0000] {job.py:229} INFO - Heartbeat recovered after 17.25 seconds
[2024-11-18T12:49:45.534+0000] {job.py:229} INFO - Heartbeat recovered after 14.57 seconds
[2024-11-18T12:49:49.032+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naphat' AIRFLOW_CTX_DAG_ID='weather_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T12:48:06.879334+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T12:48:06.879334+00:00'
[2024-11-18T12:49:49.052+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T12:49:50.428+0000] {base.py:84} INFO - Retrieving connection 'postgres_db'
[2024-11-18T12:49:51.140+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-18T12:49:51.401+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T12:49:51.441+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_pipeline, task_id=load_weather_data, run_id=manual__2024-11-18T12:48:06.879334+00:00, execution_date=20241118T124806, start_date=20241118T124918, end_date=20241118T124951
[2024-11-18T12:49:53.187+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T12:49:53.674+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
