[2024-11-18T12:01:35.812+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T12:01:36.185+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_pipeline.load_weather_data manual__2024-11-18T12:00:59.875495+00:00 [queued]>
[2024-11-18T12:01:36.281+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_pipeline.load_weather_data manual__2024-11-18T12:00:59.875495+00:00 [queued]>
[2024-11-18T12:01:36.282+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-11-18T12:01:36.491+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): load_weather_data> on 2024-11-18 12:00:59.875495+00:00
[2024-11-18T12:01:36.606+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_pipeline', 'load_weather_data', 'manual__2024-11-18T12:00:59.875495+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl.py', '--cfg-path', '/tmp/tmp2hs2ibw4']
[2024-11-18T12:01:36.627+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1989) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-18T12:01:36.636+0000] {standard_task_runner.py:72} INFO - Started process 1990 to run task
[2024-11-18T12:01:36.633+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask load_weather_data
[2024-11-18T12:01:37.111+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_etl_pipeline.load_weather_data manual__2024-11-18T12:00:59.875495+00:00 [running]> on host 527ca48b98a5
[2024-11-18T12:01:39.151+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naphat' AIRFLOW_CTX_DAG_ID='weather_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T12:00:59.875495+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T12:00:59.875495+00:00'
[2024-11-18T12:01:39.161+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T12:01:39.336+0000] {base.py:84} INFO - Retrieving connection 'postgres_db'
[2024-11-18T12:01:39.832+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-18T12:01:39.923+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T12:01:39.929+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_etl_pipeline, task_id=load_weather_data, run_id=manual__2024-11-18T12:00:59.875495+00:00, execution_date=20241118T120059, start_date=20241118T120136, end_date=20241118T120139
[2024-11-18T12:01:40.138+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T12:01:40.436+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T12:01:40.453+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
